<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Car-Sport [
    <!ELEMENT Car-Sport (car*)>
    <!ELEMENT car (name,price)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
]>
<Car-Sport>
    <car>
        <name>Toyota Supra</name>
        <price>1.52 Crore</price>

    </car>
    <car>
        <name>Porsche Cayenne</name>
        <price>6.3 Crore</price>

    </car>
    <car>
        <name>Audi R8</name>
        <price>7.12 Crore</price>

    </car>
    <car>
        <name>Nissan GT-R</name>
        <price>4.14 Crore</price>

    </car>
    <car>
        <name>Range Rover</name>
        <price>14.8 Crore</price>

    </car>
    <car>
        <name>Porsche Panamera</name>
        <price>16.8 Crore</price>

    </car>
    <car>
        <name>Ford Mustang</name>
        <price>3.9 Crore</price>

    </car>
    <car>
        <name>BMW i8</name>
        <price>3.0 Crore</price>

    </car>
    <car>
        <name>Ford Mustang</name>
        <price>3.9 Crore</price>

    </car>
    <car>
        <name>Daihatsu Copen </name>
        <price>15.1 Lacs</price>

    </car>
    <car>
        <name>Porsche 911</name>
        <price>12.9 Crore</price>

    </car>
    <car>
        <name>Honda CR-Z Sports Hybrid</name>
        <price>29.6 Lacs</price>

    </car>
    <car>
        <name>Porsche Cayman</name>
        <price>3.21 Crore</price>

    </car>
    <car>
        <name>Porsche Boxster</name>
        <price>7.1 Crore</price>

    </car>
    <car>
        <name>Bugatti Chiron</name>
        <price>109.65 Crore</price>

    </car>
    <car>
        <name>Lexus CT200h</name>
        <price>57.8 Lacs</price>

    </car>
    <car>
        <name>Toyota Supra</name>
        <price>1.52 Crore</price>

    </car>
    <car>
        <name>Porsche Cayenne</name>
        <price>6.3 Crore</price>

    </car>
    <car>
        <name>Audi R8</name>
        <price>7.12 Crore</price>

    </car>
    <car>
        <name>Nissan GT-R</name>
        <price>4.14 Crore</price>

    </car>
    <car>
        <name>Range Rover</name>
        <price>14.8 Crore</price>

    </car>
    <car>
        <name>Porsche Panamera</name>
        <price>16.8 Crore</price>

    </car>
    <car>
        <name>Ford Mustang</name>
        <price>3.9 Crore</price>

    </car>
    <car>
        <name>BMW i8</name>
        <price>3.0 Crore</price>

    </car>
    <car>
        <name>Ford Mustang</name>
        <price>3.9 Crore</price>

    </car>
    <car>
        <name>Daihatsu Copen </name>
        <price>15.1 Lacs</price>

    </car>
    <car>
        <name>Porsche 911</name>
        <price>12.9 Crore</price>

    </car>
    <car>
        <name>Honda CR-Z Sports Hybrid</name>
        <price>29.6 Lacs</price>

    </car>
    <car>
        <name>Porsche Cayman</name>
        <price>3.21 Crore</price>

    </car>
    <car>
        <name>Porsche Boxster</name>
        <price>7.1 Crore</price>

    </car>
    <car>
        <name>Bugatti Chiron</name>
        <price>109.65 Crore</price>

    </car>
    <car>
        <name>Lexus CT200h</name>
        <price>57.8 Lacs</price>

    </car>
    
    

    
    
</Car-Sport>